version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: phpvuln-web
    ports:
        - 8085:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    links:
      - db
  
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: password123!
      MYSQL_DATABASE: noob
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./sql_db:/docker-entrypoint-initdb.d