version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: irongoat-php
    ports:
        - 8085:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    links:
      - db
  
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: password123!
      MYSQL_DATABASE: 1ccb8097d0e9ce9f154608be60224c7c
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password123!
    volumes:
      - ./sql_db:/docker-entrypoint-initdb.d